### ISSUE TITLE
We used this to make our own OL quiz :)

### ISSUE THREAD

**Issue by N3XT191** [OrienteeringIsFun/O-Quiz#1]
Hi, Marc from OL Zimmerberg (Switzerland) here!

Just wanted to let you know that we used your symbols to make our own basic quiz.

[Live version](http://quiz.bitter.li) and [GitHub Repo](https://github.com/N3XT191/olz-symbol-quiz).

Not yet sure if I'll have the time to implement some actual features like levels/progress, but we'll see...

Anyways, thanks for the great SVG symbols!!

**Comment by OrienteeringIsFun** [comment]
Hi Marc,
looks good. Nice job!
